# Generated by Django 5.2.4 on 2025-07-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashback_promositon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbacktransaction',
            name='customer_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cashbacktransaction',
            name='order_id',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
